### ISSUE TITLE
Could you please upload ChatGenTitle lora weights?

### ISSUE THREAD

**Issue by jinghan23** [WangRongsheng/ChatGenTitle#1]
Thanks for your repo and it's a good idea to tune it in academic assistance area! I would like to make it clear that you do freeze alpaca weights and tune lora weights on the arxiv datasets right? Would you like to upload ChatGenTitle weights to someplace such as huggingface website so that others can access to it?

**Comment by WangRongsheng** [comment]
Yes, it will be released soon!
