### ISSUE TITLE
请问是否有可能抓取到论文的正文进行全文理解训练？

### ISSUE THREAD

**Issue by XixuHu** [WangRongsheng/ChatGenTitle#4]
您好，我想问一下请问能否抓取到arxiv论文的pdf或者tex源码然后基于全文进行训练？感觉这样提供的帮助会更大！：）

**Comment by WangRongsheng** [comment]
理论上是可以的。但是这样庞大的数据，不管是数据清洗、后期的微调训练都需要有足够的资源。

**Comment by XixuHu** [comment]
很期待这样一个学术GPT了！期待大佬拉到更多资源！

**Comment by WangRongsheng** [comment]
♥加油！
