### ISSUE TITLE
GPU dose not support Int8 Matmul

### ISSUE THREAD

**Issue by fightingman1** [WangRongsheng/ChatGenTitle#7]
When run app.py, the terminal will be shown: ERROR: Your GPU does not support Int8 Matmul!

**Comment by WangRongsheng** [comment]
Can you share your run code with me?

**Comment by fightingman1** [comment]
I just run app.py

**Comment by WangRongsheng** [comment]
Maybe you can look this: https://colab.research.google.com/drive/1akrC4-YnYdiyD1_VK-92hncN7HS0FLf5
