### ISSUE TITLE
在colab中运行脚本最后现实Can't find 'adapter_config.json'

### ISSUE THREAD

**Issue by taowenyin** [WangRongsheng/ChatGenTitle#8]
base_model = 'decapoda-research/llama-7b-hf'
finetuned_model = 'wangrongsheng/chatgentitle-lora-cs-3-new' 

使用的是这个模型

**Comment by WangRongsheng** [comment]
检查下载是否完整：https://huggingface.co/wangrongsheng/chatgentitle-lora-cs-3-new/tree/main

**Comment by QuinnQian** [comment]
同样报错
Can't find 'adapter_config.json' at 'wangrongsheng/chatgentitle-lora-cs-6-new'

**Comment by WangRongsheng** [comment]
我进行了同样操作，并未出现您的情况，您可以多提供些信息
