### ISSUE TITLE
转换权重部分，如何实现呢

### ISSUE THREAD

**Issue by Ikaros-521** [WangRongsheng/ChatGenTitle#9]
链接的仓库 https://github.com/ymcui/Chinese-LLaMA-Alpaca#step-1-%E5%B0%86%E5%8E%9F%E7%89%88llama%E6%A8%A1%E5%9E%8B%E8%BD%AC%E6%8D%A2%E4%B8%BAhf%E6%A0%BC%E5%BC%8F
没有转换文档，旧的to_hf的程序也找不到
![6_}(MU~D9BV4F9S~ WU`9PM](https://github.com/WangRongsheng/ChatGenTitle/assets/40910637/59603861-3e06-492a-98be-b2f67aa4bbae)

**Comment by WangRongsheng** [comment]
```
pip install transformers>=4.29.1

python -m transformers.models.llama.convert_llama_weights_to_hf \
    --input_dir path_to_llama_weights --model_size 7B --output_dir path_to_llama_model
```

**Comment by Ikaros-521** [comment]
> ```
> pip install transformers>=4.29.1
> 
> python -m transformers.models.llama.convert_llama_weights_to_hf \
>     --input_dir path_to_llama_weights --model_size 7B --output_dir path_to_llama_model
> ```

谢谢作者，我回头试试
